### ISSUE TITLE
Selenium error

### ISSUE THREAD

**Issue by cartooncatfish** [cartooncatfish/tdd-with-django#1]
```
$ python functional_tests.py 
Traceback (most recent call last):
  File "/Users/mikemo/.virtualenvs/python3env/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "functional_tests.py", line 3, in <module>
    browser = webdriver.Firefox()
  File "/Users/mikemo/.virtualenvs/python3env/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 157, in __init__
    self.service.start()
  File "/Users/mikemo/.virtualenvs/python3env/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH
```

**Comment by cartooncatfish** [comment]
### [Solved]
Ref: https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path
Download the driver from https://github.com/mozilla/geckodriver/releases
Choose the right version for your OS
